name = "FrictionModels"
uuid = "c650404e-e56b-4512-a255-8b4a755875f5"
authors = ["Jason Christopherson <jchristopherson@hotmail.com> and contributors"]
version = "0.1.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"

[compat]
DifferentialEquations = "6"
Interpolations = "0.13"
LsqFit = "0.12"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
